name: ${name}
description: ${description}
author: ${author}
version: ${version}
url: ${url}
main: dev.amargos.fastmotd.bukkit.FastMOTD
api: 1.13
api-version: 1.13
softdepend: [ProtocolLib]
commands:
  fastmotd:
    description: The main FastMOTD command.