# You can join to my discord server for help!
# Discord Invite: https://discord.zenithmc.me
# My GitHub: https://github.com/DevModee
# My private discord: amargos

# Using ProtocolLib will use packets instead of events.
motd:
  enabled: true

  # Placeholders: %online_players% %max_players%
  # I Recommend use https://mctools.org/motd-creator for MOTD decoration
  motds:
    - |-
      &b&lZenithMOTD &f&lDefault &b&lMOTD
      &7Online: &a%online_players%&8/&a%max_players%
    - |-
      &aZenithMOTD Multiples MOTDS
      &d&lMost OPTIMIZED plugin in the market!

# This is the list of message shown when hovering over the player count.
# Only works on Bukkit (Requires ProtocolLib) and Velocity
sample:
  enabled: true

  # Placeholders: %online_players% %max_players%
  # I Recommend use https://mctools.org/motd-creator for MOTD decoration
  samples:
    - |-
      &b&lZenithMOTD &f&lDefault &b&lMOTD
      &7Online: &a%online_players%&8/&a%max_players%
    - |-
      &aZenithMOTD Multiples Sample
      &d&lMost OPTIMIZED plugin in the market!

# This is shown as the server version name.
# Requires ProtocolLib on Bukkit to work.
protocol:
  enabled: true

  # Protocol name
  name: "AerosCord 1.7x 1.2x"

maxplayers:
  enabled: true

  # Changes the max players value.
  maxplayers: 1500

  # Changes the max player value depending on your onlineplayers.
  # Example: 12/13 players online.
  justonemore: true

# Requires ProtocolLib on Bukkit to work.
fakeplayers:
  enabled: false

  # Sets the amount of fakeplayers.
  amount: 3

  # "STATIC": Adds the value of fakeplayers to the amount of players online.
  # "RANDOM": Adds a random amount of players between 1 and the fakeplayers value.
  # "DIVISION": Adds the amount of players online divided by the fakeplayers value.
  mode: "DIVISION"