name: ZenithMOTD
description: Easy configuration MOTD plugin.
author: Amargos
version: 2.0.0
url: https://github.com/DevModee/ZenithMOTD
main: dev.amargos.zenithstudios.bukkit.FastMOTD
api: 1.13
api-version: 1.13
softdepend: [ProtocolLib]
commands:
  fastmotd:
    description: The main FastMOTD command.